// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "platform_api.g.h"

struct _VpnPluginPlatformErrorResponse {
  GObject parent_instance;

  VpnPluginPlatformErrorCode* code;
  FlValue* field_errors;
};

G_DEFINE_TYPE(VpnPluginPlatformErrorResponse, vpn_plugin_platform_error_response, G_TYPE_OBJECT)

static void vpn_plugin_platform_error_response_dispose(GObject* object) {
  VpnPluginPlatformErrorResponse* self = VPN_PLUGIN_PLATFORM_ERROR_RESPONSE(object);
  g_clear_pointer(&self->code, g_free);
  g_clear_pointer(&self->field_errors, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_platform_error_response_parent_class)->dispose(object);
}

static void vpn_plugin_platform_error_response_init(VpnPluginPlatformErrorResponse* self) {
}

static void vpn_plugin_platform_error_response_class_init(VpnPluginPlatformErrorResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_platform_error_response_dispose;
}

VpnPluginPlatformErrorResponse* vpn_plugin_platform_error_response_new(VpnPluginPlatformErrorCode* code, FlValue* field_errors) {
  VpnPluginPlatformErrorResponse* self = VPN_PLUGIN_PLATFORM_ERROR_RESPONSE(g_object_new(vpn_plugin_platform_error_response_get_type(), nullptr));
  if (code != nullptr) {
    self->code = static_cast<VpnPluginPlatformErrorCode*>(malloc(sizeof(VpnPluginPlatformErrorCode)));
    *self->code = *code;
  }
  else {
    self->code = nullptr;
  }
  if (field_errors != nullptr) {
    self->field_errors = fl_value_ref(field_errors);
  }
  else {
    self->field_errors = nullptr;
  }
  return self;
}

VpnPluginPlatformErrorCode* vpn_plugin_platform_error_response_get_code(VpnPluginPlatformErrorResponse* self) {
  g_return_val_if_fail(VPN_PLUGIN_IS_PLATFORM_ERROR_RESPONSE(self), nullptr);
  return self->code;
}

FlValue* vpn_plugin_platform_error_response_get_field_errors(VpnPluginPlatformErrorResponse* self) {
  g_return_val_if_fail(VPN_PLUGIN_IS_PLATFORM_ERROR_RESPONSE(self), nullptr);
  return self->field_errors;
}

static FlValue* vpn_plugin_platform_error_response_to_list(VpnPluginPlatformErrorResponse* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, self->code != nullptr ? fl_value_new_custom(vpn_plugin_platform_error_code_type_id, fl_value_new_int(*self->code), (GDestroyNotify)fl_value_unref) : fl_value_new_null());
  fl_value_append_take(values, self->field_errors != nullptr ? fl_value_ref(self->field_errors) : fl_value_new_null());
  return values;
}

static VpnPluginPlatformErrorResponse* vpn_plugin_platform_error_response_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  VpnPluginPlatformErrorCode* code = nullptr;
  VpnPluginPlatformErrorCode code_value;
  if (fl_value_get_type(value0) != FL_VALUE_TYPE_NULL) {
    code_value = static_cast<VpnPluginPlatformErrorCode>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
    code = &code_value;
  }
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlValue* field_errors = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    field_errors = value1;
  }
  return vpn_plugin_platform_error_response_new(code, field_errors);
}

struct _VpnPluginPlatformFieldError {
  GObject parent_instance;

  VpnPluginPlatformFieldErrorCode code;
  VpnPluginPlatformFieldName field_name;
};

G_DEFINE_TYPE(VpnPluginPlatformFieldError, vpn_plugin_platform_field_error, G_TYPE_OBJECT)

static void vpn_plugin_platform_field_error_dispose(GObject* object) {
  G_OBJECT_CLASS(vpn_plugin_platform_field_error_parent_class)->dispose(object);
}

static void vpn_plugin_platform_field_error_init(VpnPluginPlatformFieldError* self) {
}

static void vpn_plugin_platform_field_error_class_init(VpnPluginPlatformFieldErrorClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_platform_field_error_dispose;
}

VpnPluginPlatformFieldError* vpn_plugin_platform_field_error_new(VpnPluginPlatformFieldErrorCode code, VpnPluginPlatformFieldName field_name) {
  VpnPluginPlatformFieldError* self = VPN_PLUGIN_PLATFORM_FIELD_ERROR(g_object_new(vpn_plugin_platform_field_error_get_type(), nullptr));
  self->code = code;
  self->field_name = field_name;
  return self;
}

VpnPluginPlatformFieldErrorCode vpn_plugin_platform_field_error_get_code(VpnPluginPlatformFieldError* self) {
  g_return_val_if_fail(VPN_PLUGIN_IS_PLATFORM_FIELD_ERROR(self), static_cast<VpnPluginPlatformFieldErrorCode>(0));
  return self->code;
}

VpnPluginPlatformFieldName vpn_plugin_platform_field_error_get_field_name(VpnPluginPlatformFieldError* self) {
  g_return_val_if_fail(VPN_PLUGIN_IS_PLATFORM_FIELD_ERROR(self), static_cast<VpnPluginPlatformFieldName>(0));
  return self->field_name;
}

static FlValue* vpn_plugin_platform_field_error_to_list(VpnPluginPlatformFieldError* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_custom(vpn_plugin_platform_field_error_code_type_id, fl_value_new_int(self->code), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_custom(vpn_plugin_platform_field_name_type_id, fl_value_new_int(self->field_name), (GDestroyNotify)fl_value_unref));
  return values;
}

static VpnPluginPlatformFieldError* vpn_plugin_platform_field_error_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  VpnPluginPlatformFieldErrorCode code = static_cast<VpnPluginPlatformFieldErrorCode>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  FlValue* value1 = fl_value_get_list_value(values, 1);
  VpnPluginPlatformFieldName field_name = static_cast<VpnPluginPlatformFieldName>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value1)))));
  return vpn_plugin_platform_field_error_new(code, field_name);
}

struct _VpnPluginMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(VpnPluginMessageCodec, vpn_plugin_message_codec, fl_standard_message_codec_get_type())

const int vpn_plugin_vpn_manager_state_type_id = 129;
const int vpn_plugin_platform_error_code_type_id = 130;
const int vpn_plugin_platform_field_error_code_type_id = 131;
const int vpn_plugin_platform_field_name_type_id = 132;
const int vpn_plugin_platform_error_response_type_id = 133;
const int vpn_plugin_platform_field_error_type_id = 134;

static gboolean vpn_plugin_message_codec_write_vpn_plugin_vpn_manager_state(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = vpn_plugin_vpn_manager_state_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean vpn_plugin_message_codec_write_vpn_plugin_platform_error_code(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = vpn_plugin_platform_error_code_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean vpn_plugin_message_codec_write_vpn_plugin_platform_field_error_code(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = vpn_plugin_platform_field_error_code_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean vpn_plugin_message_codec_write_vpn_plugin_platform_field_name(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = vpn_plugin_platform_field_name_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean vpn_plugin_message_codec_write_vpn_plugin_platform_error_response(FlStandardMessageCodec* codec, GByteArray* buffer, VpnPluginPlatformErrorResponse* value, GError** error) {
  uint8_t type = vpn_plugin_platform_error_response_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = vpn_plugin_platform_error_response_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean vpn_plugin_message_codec_write_vpn_plugin_platform_field_error(FlStandardMessageCodec* codec, GByteArray* buffer, VpnPluginPlatformFieldError* value, GError** error) {
  uint8_t type = vpn_plugin_platform_field_error_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = vpn_plugin_platform_field_error_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean vpn_plugin_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case vpn_plugin_vpn_manager_state_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_vpn_manager_state(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case vpn_plugin_platform_error_code_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_platform_error_code(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case vpn_plugin_platform_field_error_code_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_platform_field_error_code(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case vpn_plugin_platform_field_name_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_platform_field_name(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case vpn_plugin_platform_error_response_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_platform_error_response(codec, buffer, VPN_PLUGIN_PLATFORM_ERROR_RESPONSE(fl_value_get_custom_value_object(value)), error);
      case vpn_plugin_platform_field_error_type_id:
        return vpn_plugin_message_codec_write_vpn_plugin_platform_field_error(codec, buffer, VPN_PLUGIN_PLATFORM_FIELD_ERROR(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(vpn_plugin_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_vpn_manager_state(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(vpn_plugin_vpn_manager_state_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_platform_error_code(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(vpn_plugin_platform_error_code_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_platform_field_error_code(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(vpn_plugin_platform_field_error_code_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_platform_field_name(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(vpn_plugin_platform_field_name_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_platform_error_response(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(VpnPluginPlatformErrorResponse) value = vpn_plugin_platform_error_response_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(vpn_plugin_platform_error_response_type_id, G_OBJECT(value));
}

static FlValue* vpn_plugin_message_codec_read_vpn_plugin_platform_field_error(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(VpnPluginPlatformFieldError) value = vpn_plugin_platform_field_error_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(vpn_plugin_platform_field_error_type_id, G_OBJECT(value));
}

static FlValue* vpn_plugin_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case vpn_plugin_vpn_manager_state_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_vpn_manager_state(codec, buffer, offset, error);
    case vpn_plugin_platform_error_code_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_platform_error_code(codec, buffer, offset, error);
    case vpn_plugin_platform_field_error_code_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_platform_field_error_code(codec, buffer, offset, error);
    case vpn_plugin_platform_field_name_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_platform_field_name(codec, buffer, offset, error);
    case vpn_plugin_platform_error_response_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_platform_error_response(codec, buffer, offset, error);
    case vpn_plugin_platform_field_error_type_id:
      return vpn_plugin_message_codec_read_vpn_plugin_platform_field_error(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(vpn_plugin_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void vpn_plugin_message_codec_init(VpnPluginMessageCodec* self) {
}

static void vpn_plugin_message_codec_class_init(VpnPluginMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = vpn_plugin_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = vpn_plugin_message_codec_read_value_of_type;
}

static VpnPluginMessageCodec* vpn_plugin_message_codec_new() {
  VpnPluginMessageCodec* self = VPN_PLUGIN_MESSAGE_CODEC(g_object_new(vpn_plugin_message_codec_get_type(), nullptr));
  return self;
}

struct _VpnPluginIVpnManagerStartResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerStartResponse, vpn_plugin_i_vpn_manager_start_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_start_response_dispose(GObject* object) {
  VpnPluginIVpnManagerStartResponse* self = VPN_PLUGIN_I_VPN_MANAGER_START_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_start_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_start_response_init(VpnPluginIVpnManagerStartResponse* self) {
}

static void vpn_plugin_i_vpn_manager_start_response_class_init(VpnPluginIVpnManagerStartResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_start_response_dispose;
}

VpnPluginIVpnManagerStartResponse* vpn_plugin_i_vpn_manager_start_response_new() {
  VpnPluginIVpnManagerStartResponse* self = VPN_PLUGIN_I_VPN_MANAGER_START_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

VpnPluginIVpnManagerStartResponse* vpn_plugin_i_vpn_manager_start_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerStartResponse* self = VPN_PLUGIN_I_VPN_MANAGER_START_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManagerStopResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerStopResponse, vpn_plugin_i_vpn_manager_stop_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_stop_response_dispose(GObject* object) {
  VpnPluginIVpnManagerStopResponse* self = VPN_PLUGIN_I_VPN_MANAGER_STOP_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_stop_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_stop_response_init(VpnPluginIVpnManagerStopResponse* self) {
}

static void vpn_plugin_i_vpn_manager_stop_response_class_init(VpnPluginIVpnManagerStopResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_stop_response_dispose;
}

VpnPluginIVpnManagerStopResponse* vpn_plugin_i_vpn_manager_stop_response_new() {
  VpnPluginIVpnManagerStopResponse* self = VPN_PLUGIN_I_VPN_MANAGER_STOP_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

VpnPluginIVpnManagerStopResponse* vpn_plugin_i_vpn_manager_stop_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerStopResponse* self = VPN_PLUGIN_I_VPN_MANAGER_STOP_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManagerUpdateConfigurationResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerUpdateConfigurationResponse, vpn_plugin_i_vpn_manager_update_configuration_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_update_configuration_response_dispose(GObject* object) {
  VpnPluginIVpnManagerUpdateConfigurationResponse* self = VPN_PLUGIN_I_VPN_MANAGER_UPDATE_CONFIGURATION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_update_configuration_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_update_configuration_response_init(VpnPluginIVpnManagerUpdateConfigurationResponse* self) {
}

static void vpn_plugin_i_vpn_manager_update_configuration_response_class_init(VpnPluginIVpnManagerUpdateConfigurationResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_update_configuration_response_dispose;
}

VpnPluginIVpnManagerUpdateConfigurationResponse* vpn_plugin_i_vpn_manager_update_configuration_response_new() {
  VpnPluginIVpnManagerUpdateConfigurationResponse* self = VPN_PLUGIN_I_VPN_MANAGER_UPDATE_CONFIGURATION_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_update_configuration_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

VpnPluginIVpnManagerUpdateConfigurationResponse* vpn_plugin_i_vpn_manager_update_configuration_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerUpdateConfigurationResponse* self = VPN_PLUGIN_I_VPN_MANAGER_UPDATE_CONFIGURATION_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_update_configuration_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManagerGetCurrentStateResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerGetCurrentStateResponse, vpn_plugin_i_vpn_manager_get_current_state_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_get_current_state_response_dispose(GObject* object) {
  VpnPluginIVpnManagerGetCurrentStateResponse* self = VPN_PLUGIN_I_VPN_MANAGER_GET_CURRENT_STATE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_get_current_state_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_get_current_state_response_init(VpnPluginIVpnManagerGetCurrentStateResponse* self) {
}

static void vpn_plugin_i_vpn_manager_get_current_state_response_class_init(VpnPluginIVpnManagerGetCurrentStateResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_get_current_state_response_dispose;
}

VpnPluginIVpnManagerGetCurrentStateResponse* vpn_plugin_i_vpn_manager_get_current_state_response_new(VpnPluginVpnManagerState return_value) {
  VpnPluginIVpnManagerGetCurrentStateResponse* self = VPN_PLUGIN_I_VPN_MANAGER_GET_CURRENT_STATE_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_get_current_state_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(vpn_plugin_vpn_manager_state_type_id, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

VpnPluginIVpnManagerGetCurrentStateResponse* vpn_plugin_i_vpn_manager_get_current_state_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerGetCurrentStateResponse* self = VPN_PLUGIN_I_VPN_MANAGER_GET_CURRENT_STATE_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_get_current_state_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManagerExportLogsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerExportLogsResponse, vpn_plugin_i_vpn_manager_export_logs_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_export_logs_response_dispose(GObject* object) {
  VpnPluginIVpnManagerExportLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_EXPORT_LOGS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_export_logs_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_export_logs_response_init(VpnPluginIVpnManagerExportLogsResponse* self) {
}

static void vpn_plugin_i_vpn_manager_export_logs_response_class_init(VpnPluginIVpnManagerExportLogsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_export_logs_response_dispose;
}

VpnPluginIVpnManagerExportLogsResponse* vpn_plugin_i_vpn_manager_export_logs_response_new(FlValue* return_value) {
  VpnPluginIVpnManagerExportLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_EXPORT_LOGS_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_export_logs_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

VpnPluginIVpnManagerExportLogsResponse* vpn_plugin_i_vpn_manager_export_logs_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerExportLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_EXPORT_LOGS_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_export_logs_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManagerClearLogsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIVpnManagerClearLogsResponse, vpn_plugin_i_vpn_manager_clear_logs_response, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_clear_logs_response_dispose(GObject* object) {
  VpnPluginIVpnManagerClearLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_CLEAR_LOGS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_clear_logs_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_clear_logs_response_init(VpnPluginIVpnManagerClearLogsResponse* self) {
}

static void vpn_plugin_i_vpn_manager_clear_logs_response_class_init(VpnPluginIVpnManagerClearLogsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_clear_logs_response_dispose;
}

VpnPluginIVpnManagerClearLogsResponse* vpn_plugin_i_vpn_manager_clear_logs_response_new() {
  VpnPluginIVpnManagerClearLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_CLEAR_LOGS_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_clear_logs_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

VpnPluginIVpnManagerClearLogsResponse* vpn_plugin_i_vpn_manager_clear_logs_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIVpnManagerClearLogsResponse* self = VPN_PLUGIN_I_VPN_MANAGER_CLEAR_LOGS_RESPONSE(g_object_new(vpn_plugin_i_vpn_manager_clear_logs_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIVpnManager {
  GObject parent_instance;

  const VpnPluginIVpnManagerVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(VpnPluginIVpnManager, vpn_plugin_i_vpn_manager, G_TYPE_OBJECT)

static void vpn_plugin_i_vpn_manager_dispose(GObject* object) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(vpn_plugin_i_vpn_manager_parent_class)->dispose(object);
}

static void vpn_plugin_i_vpn_manager_init(VpnPluginIVpnManager* self) {
}

static void vpn_plugin_i_vpn_manager_class_init(VpnPluginIVpnManagerClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_vpn_manager_dispose;
}

static VpnPluginIVpnManager* vpn_plugin_i_vpn_manager_new(const VpnPluginIVpnManagerVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(g_object_new(vpn_plugin_i_vpn_manager_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void vpn_plugin_i_vpn_manager_start_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->start == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* config = fl_value_get_string(value0);
  g_autoptr(VpnPluginIVpnManagerStartResponse) response = self->vtable->start(config, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "start");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "start", error->message);
  }
}

static void vpn_plugin_i_vpn_manager_stop_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->stop == nullptr) {
    return;
  }

  g_autoptr(VpnPluginIVpnManagerStopResponse) response = self->vtable->stop(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "stop");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "stop", error->message);
  }
}

static void vpn_plugin_i_vpn_manager_update_configuration_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->update_configuration == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* config = fl_value_get_string(value0);
  g_autoptr(VpnPluginIVpnManagerUpdateConfigurationResponse) response = self->vtable->update_configuration(config, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "updateConfiguration");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "updateConfiguration", error->message);
  }
}

static void vpn_plugin_i_vpn_manager_get_current_state_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->get_current_state == nullptr) {
    return;
  }

  g_autoptr(VpnPluginIVpnManagerGetCurrentStateResponse) response = self->vtable->get_current_state(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "getCurrentState");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "getCurrentState", error->message);
  }
}

static void vpn_plugin_i_vpn_manager_export_logs_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->export_logs == nullptr) {
    return;
  }

  g_autoptr(VpnPluginIVpnManagerExportLogsResponse) response = self->vtable->export_logs(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "exportLogs");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "exportLogs", error->message);
  }
}

static void vpn_plugin_i_vpn_manager_clear_logs_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIVpnManager* self = VPN_PLUGIN_I_VPN_MANAGER(user_data);

  if (self->vtable == nullptr || self->vtable->clear_logs == nullptr) {
    return;
  }

  g_autoptr(VpnPluginIVpnManagerClearLogsResponse) response = self->vtable->clear_logs(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IVpnManager", "clearLogs");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IVpnManager", "clearLogs", error->message);
  }
}

void vpn_plugin_i_vpn_manager_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const VpnPluginIVpnManagerVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(VpnPluginIVpnManager) api_data = vpn_plugin_i_vpn_manager_new(vtable, user_data, user_data_free_func);

  g_autoptr(VpnPluginMessageCodec) codec = vpn_plugin_message_codec_new();
  g_autofree gchar* start_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.start%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_channel = fl_basic_message_channel_new(messenger, start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_channel, vpn_plugin_i_vpn_manager_start_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* stop_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.stop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_channel = fl_basic_message_channel_new(messenger, stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_channel, vpn_plugin_i_vpn_manager_stop_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* update_configuration_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_configuration_channel = fl_basic_message_channel_new(messenger, update_configuration_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_configuration_channel, vpn_plugin_i_vpn_manager_update_configuration_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* get_current_state_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_current_state_channel = fl_basic_message_channel_new(messenger, get_current_state_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_current_state_channel, vpn_plugin_i_vpn_manager_get_current_state_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* export_logs_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.exportLogs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) export_logs_channel = fl_basic_message_channel_new(messenger, export_logs_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(export_logs_channel, vpn_plugin_i_vpn_manager_export_logs_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* clear_logs_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.clearLogs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_logs_channel = fl_basic_message_channel_new(messenger, clear_logs_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_logs_channel, vpn_plugin_i_vpn_manager_clear_logs_cb, g_object_ref(api_data), g_object_unref);
}

void vpn_plugin_i_vpn_manager_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(VpnPluginMessageCodec) codec = vpn_plugin_message_codec_new();
  g_autofree gchar* start_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.start%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_channel = fl_basic_message_channel_new(messenger, start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* stop_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.stop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_channel = fl_basic_message_channel_new(messenger, stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* update_configuration_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) update_configuration_channel = fl_basic_message_channel_new(messenger, update_configuration_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(update_configuration_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* get_current_state_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_current_state_channel = fl_basic_message_channel_new(messenger, get_current_state_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_current_state_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* export_logs_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.exportLogs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) export_logs_channel = fl_basic_message_channel_new(messenger, export_logs_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(export_logs_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* clear_logs_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IVpnManager.clearLogs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_logs_channel = fl_basic_message_channel_new(messenger, clear_logs_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_logs_channel, nullptr, nullptr, nullptr);
}

struct _VpnPluginIDeepLinkDecodeResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(VpnPluginIDeepLinkDecodeResponse, vpn_plugin_i_deep_link_decode_response, G_TYPE_OBJECT)

static void vpn_plugin_i_deep_link_decode_response_dispose(GObject* object) {
  VpnPluginIDeepLinkDecodeResponse* self = VPN_PLUGIN_I_DEEP_LINK_DECODE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(vpn_plugin_i_deep_link_decode_response_parent_class)->dispose(object);
}

static void vpn_plugin_i_deep_link_decode_response_init(VpnPluginIDeepLinkDecodeResponse* self) {
}

static void vpn_plugin_i_deep_link_decode_response_class_init(VpnPluginIDeepLinkDecodeResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_deep_link_decode_response_dispose;
}

VpnPluginIDeepLinkDecodeResponse* vpn_plugin_i_deep_link_decode_response_new(const gchar* return_value) {
  VpnPluginIDeepLinkDecodeResponse* self = VPN_PLUGIN_I_DEEP_LINK_DECODE_RESPONSE(g_object_new(vpn_plugin_i_deep_link_decode_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

VpnPluginIDeepLinkDecodeResponse* vpn_plugin_i_deep_link_decode_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  VpnPluginIDeepLinkDecodeResponse* self = VPN_PLUGIN_I_DEEP_LINK_DECODE_RESPONSE(g_object_new(vpn_plugin_i_deep_link_decode_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _VpnPluginIDeepLink {
  GObject parent_instance;

  const VpnPluginIDeepLinkVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(VpnPluginIDeepLink, vpn_plugin_i_deep_link, G_TYPE_OBJECT)

static void vpn_plugin_i_deep_link_dispose(GObject* object) {
  VpnPluginIDeepLink* self = VPN_PLUGIN_I_DEEP_LINK(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(vpn_plugin_i_deep_link_parent_class)->dispose(object);
}

static void vpn_plugin_i_deep_link_init(VpnPluginIDeepLink* self) {
}

static void vpn_plugin_i_deep_link_class_init(VpnPluginIDeepLinkClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = vpn_plugin_i_deep_link_dispose;
}

static VpnPluginIDeepLink* vpn_plugin_i_deep_link_new(const VpnPluginIDeepLinkVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  VpnPluginIDeepLink* self = VPN_PLUGIN_I_DEEP_LINK(g_object_new(vpn_plugin_i_deep_link_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void vpn_plugin_i_deep_link_decode_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  VpnPluginIDeepLink* self = VPN_PLUGIN_I_DEEP_LINK(user_data);

  if (self->vtable == nullptr || self->vtable->decode == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* uri = fl_value_get_string(value0);
  g_autoptr(VpnPluginIDeepLinkDecodeResponse) response = self->vtable->decode(uri, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "IDeepLink", "decode");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "IDeepLink", "decode", error->message);
  }
}

void vpn_plugin_i_deep_link_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const VpnPluginIDeepLinkVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(VpnPluginIDeepLink) api_data = vpn_plugin_i_deep_link_new(vtable, user_data, user_data_free_func);

  g_autoptr(VpnPluginMessageCodec) codec = vpn_plugin_message_codec_new();
  g_autofree gchar* decode_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IDeepLink.decode%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) decode_channel = fl_basic_message_channel_new(messenger, decode_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(decode_channel, vpn_plugin_i_deep_link_decode_cb, g_object_ref(api_data), g_object_unref);
}

void vpn_plugin_i_deep_link_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(VpnPluginMessageCodec) codec = vpn_plugin_message_codec_new();
  g_autofree gchar* decode_channel_name = g_strdup_printf("dev.flutter.pigeon.vpn_plugin.IDeepLink.decode%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) decode_channel = fl_basic_message_channel_new(messenger, decode_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(decode_channel, nullptr, nullptr, nullptr);
}
