#include "system_dns.h"

#include <gtest/gtest.h>
#include <sys/stat.h>
#include <unistd.h>

#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace cattunnel_helper {
namespace {

std::string Read(const std::string& path) {
    std::ifstream in(path);
    std::ostringstream out;
    out << in.rdbuf();
    return out.str();
}

bool Exists(const std::string& path) {
    struct stat st{};
    return lstat(path.c_str(), &st) == 0;
}

/** A temp "system": resolv.conf, backup and drop-in paths, and scripted commands. */
struct FakeSystem {
    std::string dir;
    DnsPaths paths;
    std::map<std::string, int> active;  // unit -> systemctl is-active exit code
    std::vector<std::string> commands;

    FakeSystem() {
        char tmpl[] = "/tmp/ctdnsXXXXXX";
        dir = mkdtemp(tmpl);
        mkdir((dir + "/etc").c_str(), 0755);
        paths.resolv_conf = dir + "/etc/resolv.conf";
        paths.backup = dir + "/var/lib/cattunnel/resolv.conf.backup";
        paths.nm_drop_in = dir + "/run/NetworkManager/conf.d/90-cattunnel-dns.conf";
        mkdir((dir + "/var").c_str(), 0755);
        mkdir((dir + "/var/lib").c_str(), 0755);
        mkdir((dir + "/run").c_str(), 0755);
        mkdir((dir + "/run/NetworkManager").c_str(), 0755);
    }

    SystemDns Dns() {
        return SystemDns(paths, [this](const std::vector<std::string>& argv) {
            std::string line;
            for (size_t i = 1; i < argv.size(); ++i) line += (i > 1 ? " " : "") + argv[i];
            commands.push_back(line);
            if (argv[0] == paths.systemctl) {
                auto it = active.find(argv.back());
                return it == active.end() ? 3 : it->second;
            }
            return 0;  // nmcli
        });
    }
};

constexpr const char* kNetworkManagerResolvConf = "# Generated by NetworkManager\nnameserver 192.168.1.1\n";

TEST(SystemDns, NetworkManagerPausedAndGivenBack) {
    FakeSystem sys;
    std::ofstream(sys.paths.resolv_conf) << kNetworkManagerResolvConf;
    sys.active["NetworkManager"] = 0;
    SystemDns dns = sys.Dns();

    std::string log = dns.Apply(kTunnelDnsServers);
    EXPECT_NE(log.find("NetworkManager paused"), std::string::npos) << log;
    EXPECT_NE(Read(sys.paths.nm_drop_in).find("dns=none"), std::string::npos);
    EXPECT_EQ(Read(sys.paths.resolv_conf).find("192.168.1.1"), std::string::npos);
    EXPECT_NE(Read(sys.paths.resolv_conf).find("nameserver 46.243.231.30\nnameserver 46.243.231.31\n"),
              std::string::npos);
    EXPECT_EQ(sys.commands.back(), "general reload conf");

    log = dns.Restore();
    EXPECT_NE(log.find("restored"), std::string::npos) << log;
    EXPECT_NE(log.find("NetworkManager manages DNS again"), std::string::npos) << log;
    EXPECT_EQ(Read(sys.paths.resolv_conf), kNetworkManagerResolvConf);
    EXPECT_FALSE(Exists(sys.paths.nm_drop_in));
    EXPECT_FALSE(Exists(sys.paths.backup));
    EXPECT_EQ(sys.commands.back(), "general reload conf,dns-rc");

    EXPECT_EQ(dns.Restore(), "");  // nothing left to undo
}

TEST(SystemDns, ResolvedIsLeftToTheClient) {
    FakeSystem sys;
    ASSERT_EQ(symlink("/run/systemd/resolve/stub-resolv.conf", sys.paths.resolv_conf.c_str()), 0);
    sys.active["systemd-resolved"] = 0;
    sys.active["NetworkManager"] = 0;
    SystemDns dns = sys.Dns();

    EXPECT_NE(dns.Apply(kTunnelDnsServers).find("systemd-resolved"), std::string::npos);
    EXPECT_FALSE(Exists(sys.paths.backup));
    EXPECT_FALSE(Exists(sys.paths.nm_drop_in));
    char target[256] = {};
    ASSERT_GT(readlink(sys.paths.resolv_conf.c_str(), target, sizeof(target) - 1), 0);
    EXPECT_STREQ(target, "/run/systemd/resolve/stub-resolv.conf");
    EXPECT_EQ(dns.Restore(), "");
}

TEST(SystemDns, InactiveResolvedDoesNotCount) {
    // A leftover stub link while resolved is stopped: glibc can't use it,
    // so we must still write resolv.conf - and put the link back after.
    FakeSystem sys;
    ASSERT_EQ(symlink("/run/systemd/resolve/stub-resolv.conf", sys.paths.resolv_conf.c_str()), 0);
    SystemDns dns = sys.Dns();

    EXPECT_NE(dns.Apply(kTunnelDnsServers).find("replaced"), std::string::npos);
    EXPECT_NE(Read(sys.paths.resolv_conf).find("46.243.231.30"), std::string::npos);
    dns.Restore();
    char target[256] = {};
    ASSERT_GT(readlink(sys.paths.resolv_conf.c_str(), target, sizeof(target) - 1), 0);
    EXPECT_STREQ(target, "/run/systemd/resolve/stub-resolv.conf");
}

TEST(SystemDns, PlainFileWithoutNetworkManager) {
    FakeSystem sys;
    std::ofstream(sys.paths.resolv_conf) << "nameserver 9.9.9.9\n";
    SystemDns dns = sys.Dns();

    EXPECT_NE(dns.Apply(kTunnelDnsServers).find("replaced for the session"), std::string::npos);
    EXPECT_FALSE(Exists(sys.paths.nm_drop_in));
    for (const auto& command : sys.commands) EXPECT_EQ(command.find("general reload"), std::string::npos);
    dns.Restore();
    EXPECT_EQ(Read(sys.paths.resolv_conf), "nameserver 9.9.9.9\n");
}

TEST(SystemDns, CrashLeftoversAreUndoneAndTheOriginalIsNeverLost) {
    FakeSystem sys;
    std::ofstream(sys.paths.resolv_conf) << kNetworkManagerResolvConf;
    sys.active["NetworkManager"] = 0;
    {
        SystemDns first = sys.Dns();
        first.Apply(kTunnelDnsServers);
        first.Apply(kTunnelDnsServers);  // a second start in the same session: backup kept
    }  // the helper "crashes" here - nothing restored

    SystemDns after_restart = sys.Dns();
    std::string log = after_restart.Restore();  // what the helper does at startup
    EXPECT_NE(log.find("restored"), std::string::npos) << log;
    EXPECT_EQ(Read(sys.paths.resolv_conf), kNetworkManagerResolvConf);
    EXPECT_FALSE(Exists(sys.paths.nm_drop_in));
}

TEST(SystemDns, CliRoutingCleanupMirrorsTheClientsTeardown) {
    std::vector<std::string> commands;
    CleanUpCliRouting([&](const std::vector<std::string>& argv) {
        std::string line;
        for (const auto& arg : argv) line += (line.empty() ? "" : " ") + arg;
        commands.push_back(line);
        return 2;  // "no such rule" - ignored
    });
    ASSERT_EQ(commands.size(), 8u);
    EXPECT_EQ(commands[0], "/usr/sbin/ip -4 route flush table 880");
    EXPECT_EQ(commands[1], "/usr/sbin/ip -4 rule del prio 30801 lookup 880");
    EXPECT_EQ(commands[7], "/usr/sbin/ip -6 rule del prio 30800 sport 5900-5920 lookup main");
}

TEST(SystemDns, RunCommandNeedsAnAbsolutePath) {
    EXPECT_EQ(RunCommand({"true"}), -1);
    EXPECT_EQ(RunCommand({"/bin/true"}), 0);
    EXPECT_EQ(RunCommand({"/bin/false"}), 1);
}

}  // namespace
}  // namespace cattunnel_helper
